//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string username { get; set; }
        public string password { get; set; }
        public string hoten { get; set; }
        public string daily { get; set; }
        public string chinhanh { get; set; }
        public string role { get; set; }
        public bool doimatkhau { get; set; }
        public System.DateTime ngaydoimk { get; set; }
        public bool trangthai { get; set; }
        public string khoi { get; set; }
        public string nguoitao { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string nguoicapnhat { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
    }
}
