//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chinhanh
    {
        public int Id { get; set; }
        public string chinhanh1 { get; set; }
        public string tencn { get; set; }
        public string diachi { get; set; }
        public string thanhpho { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
        public string masothue { get; set; }
        public bool trangthai { get; set; }
    }
}
