//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmdaily
    {
        public int Id { get; set; }
        public string Daily { get; set; }
        public string TenDaily { get; set; }
        public string Diachi { get; set; }
        public string Dienthoai { get; set; }
        public string fax { get; set; }
        public string chinhanh { get; set; }
        public bool trangthai { get; set; }
    }
}
