//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class doanhthuSaleQuay
    {
        public int stt { get; set; }
        public string nguoixuatve { get; set; }
        public Nullable<decimal> doanhso { get; set; }
        public Nullable<decimal> thucthu { get; set; }
    }
}
