//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class doanhthuDoanChitiet
    {
        public long id { get; set; }
        public Nullable<int> vetourid { get; set; }
        public Nullable<int> stt { get; set; }
        public string serial { get; set; }
        public string tenkhach { get; set; }
        public string diachi { get; set; }
        public string diemdon { get; set; }
        public Nullable<decimal> giave { get; set; }
        public Nullable<decimal> thucthu { get; set; }
        public Nullable<decimal> congno { get; set; }
        public string ghichu { get; set; }
    }
}
