//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class doanhthuSaleChitiet
    {
        public long stt { get; set; }
        public string chinhanh { get; set; }
        public string sgtcode { get; set; }
        public string tuyentq { get; set; }
        public string tenkhach { get; set; }
        public Nullable<int> chiemcho { get; set; }
        public Nullable<decimal> doanhthu { get; set; }
        public Nullable<decimal> thucthu { get; set; }
        public string nguoixuatve { get; set; }
    }
}
