//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class doanhthuQuayChitiet
    {
        public long stt { get; set; }
        public string chinhanh { get; set; }
        public string sgtcode { get; set; }
        public string serial { get; set; }
        public string tenkhach { get; set; }
        public string hanhtrinh { get; set; }
        public string ngaydi { get; set; }
        public string ngayve { get; set; }
        public Nullable<decimal> giave { get; set; }
        public string nguoiban { get; set; }
    }
}
