//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class doanhthuDoanNgayDi
    {
        public long stt { get; set; }
        public string sgtcode { get; set; }
        public string tuyentq { get; set; }
        public Nullable<System.DateTime> batdau { get; set; }
        public Nullable<System.DateTime> ketthuc { get; set; }
        public Nullable<int> sokhach { get; set; }
        public Nullable<decimal> doanhthu { get; set; }
    }
}
