//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongkewebchitiet
    {
        public long stt { get; set; }
        public string sgtcode { get; set; }
        public string hanhtrinh { get; set; }
        public Nullable<System.DateTime> ngaydi { get; set; }
        public Nullable<System.DateTime> ngayve { get; set; }
        public string tenkhach { get; set; }
        public string serial { get; set; }
        public string huyve { get; set; }
        public Nullable<decimal> doanhso { get; set; }
        public string nguoixuatve { get; set; }
        public string dailyxuatve { get; set; }
        public string kenhgd { get; set; }
    }
}
