//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongkeweb
    {
        public string chinhanh { get; set; }
        public Nullable<int> taove { get; set; }
        public Nullable<int> tuhuy { get; set; }
        public Nullable<int> chuaxuatve { get; set; }
        public Nullable<int> thanhcong { get; set; }
        public Nullable<int> huy { get; set; }
    }
}
