//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuyentqNgaydi
    {
        public string chinhanh { get; set; }
        public string tuyentq { get; set; }
        public int skkl { get; set; }
        public decimal dtkl { get; set; }
        public int skkd { get; set; }
        public decimal dtkd { get; set; }
        public int tongkhach { get; set; }
        public decimal tongdoanhthu { get; set; }
    }
}
