//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuyentqNgaydi
    {
        public long stt { get; set; }
        public string chinhanh { get; set; }
        public string tuyentq { get; set; }
        public Nullable<int> skkl { get; set; }
        public Nullable<decimal> dtkl { get; set; }
        public Nullable<int> skkd { get; set; }
        public Nullable<decimal> dtkd { get; set; }
        public Nullable<int> tongkhach { get; set; }
        public Nullable<decimal> tongdoanhthu { get; set; }
    }
}
